"""rename brewery/style to name/type, type and volume not null

Revision ID: 80f4ab5eab9f
Revises: e9d5e5b10ecd
Create Date: 2026-05-19 18:32:02.227844

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "80f4ab5eab9f"
down_revision: str | None = "e9d5e5b10ecd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("entry", sa.Column("name", sa.String(length=255), nullable=True))
    op.add_column("entry", sa.Column("type", sa.String(length=100), nullable=False))
    op.alter_column("entry", "volume", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False)
    op.drop_column("entry", "style")
    op.drop_column("entry", "brewery")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("entry", sa.Column("brewery", sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column("entry", sa.Column("style", sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.alter_column("entry", "volume", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True)
    op.drop_column("entry", "type")
    op.drop_column("entry", "name")
    # ### end Alembic commands ###
