"""add bar table (OSM referential)

Revision ID: d5b01bf3e70d
Revises: f3a8b2c91d04
Create Date: 2026-06-11 20:30:49.198988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5b01bf3e70d'
down_revision: Union[str, None] = 'f3a8b2c91d04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('osm_id', sa.BigInteger(), nullable=False),
    sa.Column('osm_type', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('amenity', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('postcode', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('osm_type', 'osm_id', name='uq_bar_osm_type_osm_id')
    )
    op.create_index(op.f('ix_bar_city'), 'bar', ['city'], unique=False)
    op.create_index(op.f('ix_bar_id'), 'bar', ['id'], unique=False)
    op.create_index(op.f('ix_bar_name'), 'bar', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bar_name'), table_name='bar')
    op.drop_index(op.f('ix_bar_id'), table_name='bar')
    op.drop_index(op.f('ix_bar_city'), table_name='bar')
    op.drop_table('bar')
    # ### end Alembic commands ###
