"""rename datetime to drink_datetime

Revision ID: e9d5e5b10ecd
Revises: aa720ccae86d
Create Date: 2026-05-19 18:26:52.776598

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e9d5e5b10ecd"
down_revision: str | None = "aa720ccae86d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("entry", sa.Column("drink_datetime", sa.DateTime(), nullable=False))
    op.drop_column("entry", "datetime")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("entry", sa.Column("datetime", postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column("entry", "drink_datetime")
    # ### end Alembic commands ###
